sudo: false
language: java
jdk:
  - oraclejdk8
before_install:
  - wget https://marketplace.atlassian.com/download/plugins/atlassian-plugin-sdk-tgz
  - mkdir opt
  - tar -xvzf *plugin-sdk* -C opt
  - mv opt/*plugin-sdk* opt/atlassian-plugin-sdk
  - chmod a+x opt/atlassian-plugin-sdk/bin/*
  - chmod a+x opt/atlassian-plugin-sdk/apache-maven-*/bin/*
  - export PATH=opt/atlassian-plugin-sdk/bin:opt/atlassian-plugin-sdk/apache-maven-*/bin:$PATH
  - atlas-version
install:
  #Install Atlassian libs in local Maven repo
  - atlas-mvn -q install -Dstash.version=4.0.0
  - atlas-mvn -q install
script:
  - atlas-package -q -Dstash.version=4.0.0
  - atlas-package -q
#  - ./integration-test.sh
notifications:
  email: false
